version: "3.7"

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - UPLOAD_SERVICE_HOST=http://upload-service
      - UPLOAD_SERVICE_PORT=8080
    volumes:
      - ".:/app"
      - "/opt/app/node_modules"
    ports:
      - 3001:3000
    networks:
      - chunked-file-upload-poc
networks:
  chunked-file-upload-poc:
    name: chunked-file-upload-poc
    external: true
