version: '3.7'

services:
  upload-service:
    image: test/upload-service:latest
    env_file:
      - .env
    container_name: upload-service
    ports:
      - 82:8080
    networks:
      - chunked-file-upload-poc
networks:
  chunked-file-upload-poc:
    name: chunked-file-upload-poc
    external: true
