version: '3.7'

services:
  upload-service:
    image: test/upload-service:latest
    env_file:
      - .env
    container_name: upload-service
    ports:
      - 82:8080
    networks:
      - test
networks:
  test:
    name: test
    external: true
