version: '3.8'

services:
  upload-service:
    build:
      context: .
    image: test/upload-service:latest
    environment:
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    container_name: upload-service
    ports:
      - "82:8080"
    networks:
      - test
networks:
  test:
    name: test
    external: true
