server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SiZE}
      max-request-size: ${MAX_REQUEST_SIZE}

logging:
  level:
    root: INFO
    org.springframework.web: INFO

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
